name: gdb-static-pipeline

on:
  pull_request:
    branches:
      - '*'
  push:
    tags:
      - 'v*'

jobs:
  build:
    env:
      TTY_ARG: "" # Disable interactive build mode in cicd since it does not contain a tty device.

    strategy:
      matrix: &matrix_config
        build_type: ["slim", "full"]
        architecture: ["x86_64", "arm", "aarch64", "powerpc", "mips", "mipsel"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y wget

    - name: Build
      run: make build-${{ matrix.architecture }}-${{ matrix.build_type }} -j$(nproc)

    - name: Pack
      run: make pack-${{ matrix.architecture }}-${{ matrix.build_type }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gdb-static-${{ matrix.architecture }}-${{ matrix.build_type }}
        path: build/artifacts/gdb-static*.tar.gz
        if-no-files-found: error

  test:
    needs: build
    strategy:
      matrix: *matrix_config

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        pip install pytest
        if [ "${{ matrix.architecture }}" != "x86_64" ]; then
          sudo apt-get install -y qemu-user
        fi
        case "${{ matrix.architecture }}" in
          x86_64)
            sudo apt-get install -y g++
            ;;
          aarch64)
            sudo apt-get install -y g++-aarch64-linux-gnu
            ;;
          arm)
            sudo apt-get install -y g++-arm-linux-gnueabi
            ;;
          powerpc)
            sudo apt-get install -y g++-powerpc-linux-gnu
            ;;
          mips)
            sudo apt-get install -y g++-mips-linux-gnu
            ;;
          mipsel)
            sudo apt-get install -y g++-mipsel-linux-gnu
            ;;
          *)
            echo "Unsupported architecture: ${{ matrix.architecture }}"
            exit 1
            ;;
        esac

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: gdb-static-${{ matrix.architecture }}-${{ matrix.build_type }}
        path: build/artifacts

    - name: Unpack artifact
      run: |
        mkdir -p build/artifacts/${{ matrix.architecture }}_${{ matrix.build_type }}
        tar -xzf build/artifacts/gdb-static-${{ matrix.build_type }}-${{ matrix.architecture }}.tar.gz -C build/artifacts/${{ matrix.architecture }}_${{ matrix.build_type }}

    - name: Run tests
      run: make test-${{ matrix.architecture }}-${{ matrix.build_type }}

  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        files: artifacts/**/*.tar.gz
        body: |
          There are 2 asset types:
          - Slim releases contain all of the base features.
          - Full releases also contain python & cross-architecture debugging support.
          Please note that full release binaries are bigger.

