name: gdb-static-pr-pipeline

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    env:
      TTY_ARG: "" # Disable interactive build mode in cicd since it does not contain a tty device.

    strategy:
      matrix:
        build_type: ["slim", "full"]
        architecture: ["x86_64", "arm", "aarch64", "powerpc", "mips", "mipsel"]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install -y wget

    - name: Build
      run: make build-${{ matrix.architecture }}-${{ matrix.build_type }} -j$((`nproc`+1))
